/**
 * This code was generated by Builder.io.
 */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        violet: {
          300: "#b794f4",
          600: "#7c3aed",
        },
        indigo: {
          50: "#eef2ff",
        },
        zinc: {
          100: "#f4f4f5",
        },
        gray: {
          200: "#e5e7eb",
          500: "#6b7280",
        },
        slate: {
          50: "#f8fafc",
        },
        stone: {
          950: "#0c0a09",
        },
      },
    },
  },
  plugins: [],
};
