/**
 * This code was generated by Builder.io.
 */
import React from "react";

function UserSearch() {
  return (
    <div className="flex flex-col w-full max-md:max-w-full">
      <div className="flex flex-wrap gap-2.5 items-start p-1 w-full rounded-lg border border-solid bg-neutral-100 border-stone-300 border-opacity-10 max-md:max-w-full">
        <div className="flex flex-1 shrink items-start font-semibold rounded-lg basis-0 min-w-[240px]">
          <div className="flex overflow-hidden flex-1 shrink gap-2 justify-center items-center px-5 py-2.5 w-full bg-white rounded-lg border border-solid shadow-sm basis-0 border-black border-opacity-10 min-w-[240px]">
            <div className="flex gap-2 self-stretch my-auto w-[117px]">
              <div className="grow text-sm leading-6 text-neutral-900">
                Active Users
              </div>
              <div className="overflow-hidden gap-2.5 self-stretch px-1 py-1 my-auto text-xs leading-none text-white whitespace-nowrap bg-violet-500 rounded">
                50
              </div>
            </div>
          </div>
        </div>
        <div className="flex flex-1 shrink items-start text-sm font-medium leading-6 rounded-lg basis-0 min-w-[240px] text-zinc-500">
          <div className="overflow-hidden flex-1 shrink gap-2 self-stretch px-5 py-2.5 w-full rounded-lg shadow-sm min-w-[240px]">
            Non Active Users
          </div>
        </div>
      </div>
      <div className="flex flex-col mt-6 w-full text-sm leading-none text-gray-500 max-md:max-w-full">
        <div className="flex flex-col w-full max-md:max-w-full">
          <div className="flex flex-col w-full max-md:max-w-full">
            <div className="flex gap-2 items-center px-3.5 py-3 w-full bg-white rounded-lg border border-gray-300 border-solid shadow-sm min-h-[44px] max-md:max-w-full">
              <div className="flex flex-wrap flex-1 shrink gap-3 items-center self-stretch my-auto w-full basis-0 min-w-[240px] max-md:max-w-full">
                <img
                  loading="lazy"
                  src="https://cdn.builder.io/api/v1/image/assets/TEMP/a35bce8802d4ba44b7303697e1b63985c2af438e0b68eb6df155f7df3e3cdd0c?placeholderIfAbsent=true&apiKey=740fe41628444c68b4015f1a2abbfb39"
                  alt=""
                  className="object-contain shrink-0 self-stretch my-auto w-5 aspect-[1.25]"
                />
                <label htmlFor="searchEmployees" className="sr-only">
                  Search Employees
                </label>
                <input
                  id="searchEmployees"
                  type="text"
                  placeholder="Search Employees"
                  className="self-stretch my-auto bg-transparent border-none focus:outline-none"
                />
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

export default UserSearch;
