/**
 * This code was generated by Builder.io.
 */
import React from "react";

function Header() {
  return (
    <header className="flex overflow-hidden absolute z-0 justify-center items-center self-start px-2 w-8 h-8 bg-white rounded-2xl border border-solid border-black border-opacity-10 right-[17px] top-[19px]">
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/3fcf474f8491391071061a9384f65326ce4f43858b33e0849d24ed74460b6c25?placeholderIfAbsent=true&apiKey=740fe41628444c68b4015f1a2abbfb39"
        className="object-contain self-stretch my-auto aspect-square w-[18px]"
        alt=""
      />
    </header>
  );
}

export default Header;
