/**
 * This code was generated by Builder.io.
 */
import React from "react";

function SupportMessage() {
  return (
    <div className="flex z-0 gap-1.5 items-start mt-5 max-w-full text-xs leading-4 text-gray-500 w-[406px]">
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/a239f7c26a64d6d86a6366414eacb8194ca9f89198824276928b8b4ffeb7960b?placeholderIfAbsent=true&apiKey=740fe41628444c68b4015f1a2abbfb39"
        className="object-contain shrink-0 w-5 aspect-square"
        alt=""
      />
      <p className="w-[378px]">
        Submitting this request will notify Loyaltri Support, and they'll reach
        out within 24 hours.
      </p>
    </div>
  );
}

export default SupportMessage;
